import os


class ConfigManager:
    def __init__(self, config_file):
        """Initialize with the path to the configuration file"""
        self.config_file = config_file
        self.config_data = {}

        # Automatically read the config file if it exists
        if os.path.exists(self.config_file):
            self.read_config()

    def read_config(self):
        """Read the configuration file and parse its contents"""
        try:
            with open(self.config_file, 'r') as file:
                for line in file:
                    # Skip empty lines and comments
                    line = line.strip()
                    if line and not line.startswith('#'):
                        key, value = line.split('=', 1)
                        self.config_data[key.strip()] = value.strip()
            return True
        except FileNotFoundError:
            print(f"Configuration file {self.config_file} not found.")
            return False
        except Exception as e:
            print(f"Error reading configuration: {str(e)}")
            return False

    def write_config(self):
        """Write the current configuration to the file"""
        try:
            with open(self.config_file, 'w') as file:
                # Write a header comment
                file.write("# Configuration File\n")
                file.write("# Generated by ConfigManager\n\n")

                # Write all key-value pairs
                for key, value in self.config_data.items():
                    file.write(f"{key}={value}\n")
            return True
        except Exception as e:
            print(f"Error writing configuration: {str(e)}")
            return False

    def get_value(self, key):
        """Get a value for a given key"""
        return self.config_data.get(key)

    def set_value(self, key, value):
        """Set a value for a given key"""
        self.config_data[key] = str(value)

    def remove_value(self, key):
        """Remove a key-value pair"""
        if key in self.config_data:
            del self.config_data[key]
            return True
        return False

    def create_key_value(self, key, value, comment=None):
        """
        Create a new key-value pair with an optional comment
        Returns True if created successfully, False if key already exists
        """
        if key not in self.config_data:
            # Add the new key-value pair to memory
            self.config_data[key] = str(value)

            # Check if config file exists, if not create it with header
            if not os.path.exists(self.config_file):
                with open(self.config_file, 'w') as file:
                    file.write("# Configuration File\n")
                    file.write("# Generated by ConfigManager\n\n")

            # Append the new key-value pair to the file
            with open(self.config_file, 'a') as file:
                if comment:
                    file.write(f"# {comment}\n")
                file.write(f"{key}={value}\n\n")
            return True
        return False
